# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Upgrade pip
        run: pip3 install --upgrade pip

      - name: Install setuptools
        run: pip3 install setuptools

      - name: Install requirements
        run: pip3 install -r requirements.txt

      - name: Run pylint
        run: python3 manage.py lint

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Upgrade pip
        run: pip3 install --upgrade pip

      - name: Install setuptools
        run: pip3 install setuptools

      - name: Install requirements
        run: pip3 install -r requirements.txt

      - name: Create and fill db
        run: python3 manage.py restoredb

      - name: Run django tests
        run: python3 manage.py test
